-- MySQL Script generated by MySQL Workbench
-- Thu Mar 10 09:45:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`catedratico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`catedratico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`catedratico` (
  `idCatedratico` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idCatedratico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`curso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `creditos` INT NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`calificacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`calificacion` (
  `idcalificacion` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(250) NULL,
  `calificacion` INT NOT NULL,
  `catedratico_idCatedratico` INT NOT NULL,
  `curso_codigo` INT NOT NULL,
  PRIMARY KEY (`idcalificacion`, `catedratico_idCatedratico`, `curso_codigo`),
  INDEX `fk_calificacion_catedratico_idx` (`catedratico_idCatedratico` ASC) VISIBLE,
  INDEX `fk_calificacion_curso1_idx` (`curso_codigo` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
